/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_SON_BCCH_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_SON_BCCH_TCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_SON_DCCH_TCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_SonRRCConnectionReconfigurationRequest;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module SON-RRC-Definitions in uav_rrc.asn1 */
	&asn_DEF_SON_BCCH_BCH_Message,	
	&asn_DEF_SON_BCCH_TCH_Message,	
	&asn_DEF_SON_DCCH_TCH_Message,	
	&asn_DEF_SonRRCConnectionReconfigurationRequest,	
	0
};

