/*
 * Generated by ESWINCOMPUTING easn1c 
 * And merged all header files by HeaderFileAllInOne.py.
*/

#ifndef	_SON_RRC_DEFINITIONS_H_
#define	_SON_RRC_DEFINITIONS_H_

#include "asn1c_support_lib.h"


#ifdef __cplusplus
extern "C" {
#endif


/******  NodeRouteInformation Definition Start *****/

/* NodeRouteInformation */
typedef struct NodeRouteInformation {
	OCTET_STRING_t	 nodeRouteInfo;
} NodeRouteInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeRouteInformation;

/******  NodeRouteInformation Definition End *****/

/******  SonSystemInformationBlockType1 Definition Start *****/

/* Dependencies */
typedef enum SonSystemInformationBlockType1__messageSegmentType {
	SonSystemInformationBlockType1__messageSegmentType_notLastSegment	= 0,
	SonSystemInformationBlockType1__messageSegmentType_lastSegment	= 1
} e_SonSystemInformationBlockType1__messageSegmentType;

/* SonSystemInformationBlockType1 */
typedef struct SonSystemInformationBlockType1 {
	long	 messageSequenceNumber;
	long	 messageSegmentType;
	long	 messageSegmentNumber;
	NodeRouteInformation_t	 nodeRouteInformation;
	struct SonSystemInformationBlockType1__nonCriticalExtension {
	} *nonCriticalExtension;
} SonSystemInformationBlockType1_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_messageSegmentType_111;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SonSystemInformationBlockType1;

/******  SonSystemInformationBlockType1 Definition End *****/

/******  SubnetInfo Definition Start *****/

/* Forward declarations */
struct ActiveTime;

/* SubnetInfo */
typedef struct SubnetInfo {
	long	 physCellId;
	long	 subnetFreq;
	struct ActiveTime	*leaveTime	/* OPTIONAL */;
} SubnetInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubnetInfo;

/******  SubnetInfo Definition End *****/

/******  NodeAddressIdentity Definition Start *****/

/* NodeAddressIdentity */
typedef struct NodeAddressIdentity {
	OCTET_STRING_t	 nodeSN;
} NodeAddressIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeAddressIdentity;

/******  NodeAddressIdentity Definition End *****/

/******  SonSystemInformationBlockType2 Definition Start *****/

/* Dependencies */
typedef enum SonSystemInformationBlockType2__currentNodeLeaveIndication {
	SonSystemInformationBlockType2__currentNodeLeaveIndication_false	= 0,
	SonSystemInformationBlockType2__currentNodeLeaveIndication_true	= 1
} e_SonSystemInformationBlockType2__currentNodeLeaveIndication;

/* Forward declarations */
struct OccupiedRadioFrameList;

/* SonSystemInformationBlockType2 */
typedef struct SonSystemInformationBlockType2 {
	long	 ssfnCycle;
	long	 currentNodeId;
	long	 messageSequenceNumber;
	long	 currentNodeLeaveIndication;
	SubnetInfo_t	 subnetInfo;
	NodeAddressIdentity_t	 currentNodeAddress;
	NodeAddressIdentity_t	 mainNodeAddress;
	struct OccupiedRadioFrameList	*occupiedRadioFrameList	/* OPTIONAL */;
	struct SonSystemInformationBlockType2__nonCriticalExtension {
	} *nonCriticalExtension;
} SonSystemInformationBlockType2_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_currentNodeLeaveIndication_121;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SonSystemInformationBlockType2;

/******  SonSystemInformationBlockType2 Definition End *****/

/******  SON-BCCH-TCH-MessageType Definition Start *****/

/* Dependencies */
typedef enum SON_BCCH_TCH_MessageType_PR {
	SON_BCCH_TCH_MessageType_PR_NOTHING,	/* No components present */
	SON_BCCH_TCH_MessageType_PR_c1,
	SON_BCCH_TCH_MessageType_PR_messageClassExtension
} SON_BCCH_TCH_MessageType_PR;
typedef enum SON_BCCH_TCH_MessageType__c1_PR {
	SON_BCCH_TCH_MessageType__c1_PR_NOTHING,	/* No components present */
	SON_BCCH_TCH_MessageType__c1_PR_sonsystemInformationBlockType1,
	SON_BCCH_TCH_MessageType__c1_PR_sonsystemInformationBlockType2,
	SON_BCCH_TCH_MessageType__c1_PR_spare5,
	SON_BCCH_TCH_MessageType__c1_PR_spare4,
	SON_BCCH_TCH_MessageType__c1_PR_spare3,
	SON_BCCH_TCH_MessageType__c1_PR_spare2,
	SON_BCCH_TCH_MessageType__c1_PR_spare1
} SON_BCCH_TCH_MessageType__c1_PR;

/* SON-BCCH-TCH-MessageType */
typedef struct SON_BCCH_TCH_MessageType {
	SON_BCCH_TCH_MessageType_PR present;
	union SON_BCCH_TCH_MessageType_u {
		struct SON_BCCH_TCH_MessageType__c1 {
			SON_BCCH_TCH_MessageType__c1_PR present;
			union SON_BCCH_TCH_MessageType__c1_u {
				SonSystemInformationBlockType1_t	 sonsystemInformationBlockType1;
				SonSystemInformationBlockType2_t	 sonsystemInformationBlockType2;
				NULL_t	 spare5;
				NULL_t	 spare4;
				NULL_t	 spare3;
				NULL_t	 spare2;
				NULL_t	 spare1;
			} choice;
		} c1;
		struct SON_BCCH_TCH_MessageType__messageClassExtension {
		} messageClassExtension;
	} choice;
} SON_BCCH_TCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SON_BCCH_TCH_MessageType;

/******  SON-BCCH-TCH-MessageType Definition End *****/


/******  SonMasterInformationBlock Definition Start *****/

/* Dependencies */
typedef enum SonMasterInformationBlock__bandwidth {
	SonMasterInformationBlock__bandwidth_n6	= 0,
	SonMasterInformationBlock__bandwidth_n15	= 1,
	SonMasterInformationBlock__bandwidth_n25	= 2,
	SonMasterInformationBlock__bandwidth_n50	= 3,
	SonMasterInformationBlock__bandwidth_n75	= 4,
	SonMasterInformationBlock__bandwidth_n100	= 5
} e_SonMasterInformationBlock__bandwidth;
typedef enum SonMasterInformationBlock__transmissionMode {
	SonMasterInformationBlock__transmissionMode_tm0	= 0,
	SonMasterInformationBlock__transmissionMode_tm1	= 1,
	SonMasterInformationBlock__transmissionMode_tm2	= 2,
	SonMasterInformationBlock__transmissionMode_tm3	= 3
} e_SonMasterInformationBlock__transmissionMode;
typedef enum SonMasterInformationBlock__antennaPortNum {
	SonMasterInformationBlock__antennaPortNum_ap1	= 0,
	SonMasterInformationBlock__antennaPortNum_ap2	= 1,
	SonMasterInformationBlock__antennaPortNum_ap4	= 2
} e_SonMasterInformationBlock__antennaPortNum;

/* SonMasterInformationBlock */
typedef struct SonMasterInformationBlock {
	long	 bandwidth;
	BIT_STRING_t	 systemFrameNumber;
	long	 transmissionMode;
	BIT_STRING_t	 version;
	long	 currntNodeId;
	long	 totalNodeNum;
	long	 antennaPortNum;
	long	 txPower;
	BIT_STRING_t	 macI;
	long	 sonId;
	struct SonMasterInformationBlock__nonCriticalExtension {
	} *nonCriticalExtension;
} SonMasterInformationBlock_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_bandwidth_30;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_transmissionMode_38;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_antennaPortNum_46;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SonMasterInformationBlock;

/******  SonMasterInformationBlock Definition End *****/


/******  SonRRCConnectionRequest-IEs Definition Start *****/

/* SonRRCConnectionRequest-IEs */
typedef struct SonRRCConnectionRequest_IEs {
	long	 pre_occupiedRF;
	NodeAddressIdentity_t	 accessingNodeAddress;
	NodeAddressIdentity_t	 accessedNodeAddress;
	struct SonRRCConnectionRequest_IEs__nonCriticalExtension {
	} *nonCriticalExtension;
} SonRRCConnectionRequest_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionRequest_IEs;

/******  SonRRCConnectionRequest-IEs Definition End *****/

/******  SonRRCConnectionRequest Definition Start *****/

/* Dependencies */
typedef enum SonRRCConnectionRequest__criticalExtensions_PR {
	SonRRCConnectionRequest__criticalExtensions_PR_NOTHING,	/* No components present */
	SonRRCConnectionRequest__criticalExtensions_PR_sonrrcConnectionRequest,
	SonRRCConnectionRequest__criticalExtensions_PR_criticalExtensionsFuture
} SonRRCConnectionRequest__criticalExtensions_PR;

/* SonRRCConnectionRequest */
typedef struct SonRRCConnectionRequest {
	struct SonRRCConnectionRequest__criticalExtensions {
		SonRRCConnectionRequest__criticalExtensions_PR present;
		union SonRRCConnectionRequest__criticalExtensions_u {
			SonRRCConnectionRequest_IEs_t	 sonrrcConnectionRequest;
			struct SonRRCConnectionRequest__criticalExtensions__criticalExtensionsFuture {
			} criticalExtensionsFuture;
		} choice;
	} criticalExtensions;
} SonRRCConnectionRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionRequest;

/******  SonRRCConnectionRequest Definition End *****/

/******  SonRRCConnectionReject-IEs Definition Start *****/

/* Dependencies */
typedef enum SonRRCConnectionReject_IEs__rejectCause {
	SonRRCConnectionReject_IEs__rejectCause_congestion	= 0,
	SonRRCConnectionReject_IEs__rejectCause_spare7	= 1,
	SonRRCConnectionReject_IEs__rejectCause_spare6	= 2,
	SonRRCConnectionReject_IEs__rejectCause_spare5	= 3,
	SonRRCConnectionReject_IEs__rejectCause_spare4	= 4,
	SonRRCConnectionReject_IEs__rejectCause_spare3	= 5,
	SonRRCConnectionReject_IEs__rejectCause_spare2	= 6,
	SonRRCConnectionReject_IEs__rejectCause_spare1	= 7
} e_SonRRCConnectionReject_IEs__rejectCause;

/* SonRRCConnectionReject-IEs */
typedef struct SonRRCConnectionReject_IEs {
	NodeAddressIdentity_t	 accessingNodeAddress;
	NodeAddressIdentity_t	 accessedNodeAddress;
	long	 rejectCause;
	struct SonRRCConnectionReject_IEs__nonCriticalExtension {
	} *nonCriticalExtension;
} SonRRCConnectionReject_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rejectCause_74;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReject_IEs;

/******  SonRRCConnectionReject-IEs Definition End *****/

/******  SonRRCConnectionReject Definition Start *****/

/* Dependencies */
typedef enum SonRRCConnectionReject__criticalExtensions_PR {
	SonRRCConnectionReject__criticalExtensions_PR_NOTHING,	/* No components present */
	SonRRCConnectionReject__criticalExtensions_PR_c1,
	SonRRCConnectionReject__criticalExtensions_PR_criticalExtensionsFuture
} SonRRCConnectionReject__criticalExtensions_PR;
typedef enum SonRRCConnectionReject__criticalExtensions__c1_PR {
	SonRRCConnectionReject__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	SonRRCConnectionReject__criticalExtensions__c1_PR_rrcConnectionReject,
	SonRRCConnectionReject__criticalExtensions__c1_PR_spare
} SonRRCConnectionReject__criticalExtensions__c1_PR;

/* SonRRCConnectionReject */
typedef struct SonRRCConnectionReject {
	struct SonRRCConnectionReject__criticalExtensions {
		SonRRCConnectionReject__criticalExtensions_PR present;
		union SonRRCConnectionReject__criticalExtensions_u {
			struct SonRRCConnectionReject__criticalExtensions__c1 {
				SonRRCConnectionReject__criticalExtensions__c1_PR present;
				union SonRRCConnectionReject__criticalExtensions__c1_u {
					SonRRCConnectionReject_IEs_t	 rrcConnectionReject;
					NULL_t	 spare;
				} choice;
			} c1;
			struct SonRRCConnectionReject__criticalExtensions__criticalExtensionsFuture {
			} criticalExtensionsFuture;
		} choice;
	} criticalExtensions;
} SonRRCConnectionReject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReject;

/******  SonRRCConnectionReject Definition End *****/

/******  SonRRCConnectionConfirm-IEs Definition Start *****/

/* SonRRCConnectionConfirm-IEs */
typedef struct SonRRCConnectionConfirm_IEs {
	long	 occupiedRF;
	NodeAddressIdentity_t	 accessingNodeAddress;
	NodeAddressIdentity_t	 accessedNodeAddress;
	struct SonRRCConnectionConfirm_IEs__nonCriticalExtension {
	} *nonCriticalExtension;
} SonRRCConnectionConfirm_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionConfirm_IEs;

/******  SonRRCConnectionConfirm-IEs Definition End *****/

/******  SonRRCConnectionConfirm Definition Start *****/

/* Dependencies */
typedef enum SonRRCConnectionConfirm__criticalExtensions_PR {
	SonRRCConnectionConfirm__criticalExtensions_PR_NOTHING,	/* No components present */
	SonRRCConnectionConfirm__criticalExtensions_PR_c1,
	SonRRCConnectionConfirm__criticalExtensions_PR_criticalExtensionsFuture
} SonRRCConnectionConfirm__criticalExtensions_PR;
typedef enum SonRRCConnectionConfirm__criticalExtensions__c1_PR {
	SonRRCConnectionConfirm__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	SonRRCConnectionConfirm__criticalExtensions__c1_PR_rrcConnectionConfirm,
	SonRRCConnectionConfirm__criticalExtensions__c1_PR_spare
} SonRRCConnectionConfirm__criticalExtensions__c1_PR;

/* SonRRCConnectionConfirm */
typedef struct SonRRCConnectionConfirm {
	struct SonRRCConnectionConfirm__criticalExtensions {
		SonRRCConnectionConfirm__criticalExtensions_PR present;
		union SonRRCConnectionConfirm__criticalExtensions_u {
			struct SonRRCConnectionConfirm__criticalExtensions__c1 {
				SonRRCConnectionConfirm__criticalExtensions__c1_PR present;
				union SonRRCConnectionConfirm__criticalExtensions__c1_u {
					SonRRCConnectionConfirm_IEs_t	 rrcConnectionConfirm;
					NULL_t	 spare;
				} choice;
			} c1;
			struct SonRRCConnectionConfirm__criticalExtensions__criticalExtensionsFuture {
			} criticalExtensionsFuture;
		} choice;
	} criticalExtensions;
} SonRRCConnectionConfirm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionConfirm;

/******  SonRRCConnectionConfirm Definition End *****/

/******  SON-DCCH-TCH-MessageType Definition Start *****/

/* Dependencies */
typedef enum SON_DCCH_TCH_MessageType_PR {
	SON_DCCH_TCH_MessageType_PR_NOTHING,	/* No components present */
	SON_DCCH_TCH_MessageType_PR_c1,
	SON_DCCH_TCH_MessageType_PR_messageClassExtension
} SON_DCCH_TCH_MessageType_PR;
typedef enum SON_DCCH_TCH_MessageType__c1_PR {
	SON_DCCH_TCH_MessageType__c1_PR_NOTHING,	/* No components present */
	SON_DCCH_TCH_MessageType__c1_PR_sonRrcConnectionRequest,
	SON_DCCH_TCH_MessageType__c1_PR_sonRrcConnectionReject,
	SON_DCCH_TCH_MessageType__c1_PR_sonRrcConnectionConfirm,
	SON_DCCH_TCH_MessageType__c1_PR_spare5,
	SON_DCCH_TCH_MessageType__c1_PR_spare4,
	SON_DCCH_TCH_MessageType__c1_PR_spare3,
	SON_DCCH_TCH_MessageType__c1_PR_spare2,
	SON_DCCH_TCH_MessageType__c1_PR_spare1
} SON_DCCH_TCH_MessageType__c1_PR;

/* SON-DCCH-TCH-MessageType */
typedef struct SON_DCCH_TCH_MessageType {
	SON_DCCH_TCH_MessageType_PR present;
	union SON_DCCH_TCH_MessageType_u {
		struct SON_DCCH_TCH_MessageType__c1 {
			SON_DCCH_TCH_MessageType__c1_PR present;
			union SON_DCCH_TCH_MessageType__c1_u {
				SonRRCConnectionRequest_t	 sonRrcConnectionRequest;
				SonRRCConnectionReject_t	 sonRrcConnectionReject;
				SonRRCConnectionConfirm_t	 sonRrcConnectionConfirm;
				NULL_t	 spare5;
				NULL_t	 spare4;
				NULL_t	 spare3;
				NULL_t	 spare2;
				NULL_t	 spare1;
			} choice;
		} c1;
		struct SON_DCCH_TCH_MessageType__messageClassExtension {
		} messageClassExtension;
	} choice;
} SON_DCCH_TCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SON_DCCH_TCH_MessageType;

/******  SON-DCCH-TCH-MessageType Definition End *****/

/******  SON-DCCH-TCH-Message Definition Start *****/

/* SON-DCCH-TCH-Message */
typedef struct SON_DCCH_TCH_Message {
	SON_DCCH_TCH_MessageType_t	 message;
} SON_DCCH_TCH_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SON_DCCH_TCH_Message;

/******  SON-DCCH-TCH-Message Definition End *****/


/******  SON-BCCH-TCH-Message Definition Start *****/

/* SON-BCCH-TCH-Message */
typedef struct SON_BCCH_TCH_Message {
	SON_BCCH_TCH_MessageType_t	 message;
} SON_BCCH_TCH_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SON_BCCH_TCH_Message;

/******  SON-BCCH-TCH-Message Definition End *****/


/******  ActiveTime Definition Start *****/

/* ActiveTime */
typedef struct ActiveTime {
	long	 ssfnCycle;
	long	 ssfn;
} ActiveTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActiveTime;

/******  ActiveTime Definition End *****/

/******  SonRRCConnectionReconfigurationRequest-IEs Definition Start *****/

/* Dependencies */
typedef enum SonRRCConnectionReconfigurationRequest_IEs__bandwidth {
	SonRRCConnectionReconfigurationRequest_IEs__bandwidth_n6	= 0,
	SonRRCConnectionReconfigurationRequest_IEs__bandwidth_n15	= 1,
	SonRRCConnectionReconfigurationRequest_IEs__bandwidth_n25	= 2,
	SonRRCConnectionReconfigurationRequest_IEs__bandwidth_n50	= 3,
	SonRRCConnectionReconfigurationRequest_IEs__bandwidth_n75	= 4,
	SonRRCConnectionReconfigurationRequest_IEs__bandwidth_n100	= 5
} e_SonRRCConnectionReconfigurationRequest_IEs__bandwidth;

/* SonRRCConnectionReconfigurationRequest-IEs */
typedef struct SonRRCConnectionReconfigurationRequest_IEs {
	long	 freqInfo;
	long	 bandwidth;
	long	 physCellId;
	ActiveTime_t	 activeTime;
	struct SonRRCConnectionReconfigurationRequest_IEs__nonCriticalExtension {
	} *nonCriticalExtension;
} SonRRCConnectionReconfigurationRequest_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_bandwidth_99;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReconfigurationRequest_IEs;

/******  SonRRCConnectionReconfigurationRequest-IEs Definition End *****/

/******  SonRRCConnectionReconfigurationRequest Definition Start *****/

/* Dependencies */
typedef enum SonRRCConnectionReconfigurationRequest__criticalExtensions_PR {
	SonRRCConnectionReconfigurationRequest__criticalExtensions_PR_NOTHING,	/* No components present */
	SonRRCConnectionReconfigurationRequest__criticalExtensions_PR_sonrrcConnectionReconfigurationRequest,
	SonRRCConnectionReconfigurationRequest__criticalExtensions_PR_criticalExtensionsFuture
} SonRRCConnectionReconfigurationRequest__criticalExtensions_PR;

/* SonRRCConnectionReconfigurationRequest */
typedef struct SonRRCConnectionReconfigurationRequest {
	struct SonRRCConnectionReconfigurationRequest__criticalExtensions {
		SonRRCConnectionReconfigurationRequest__criticalExtensions_PR present;
		union SonRRCConnectionReconfigurationRequest__criticalExtensions_u {
			SonRRCConnectionReconfigurationRequest_IEs_t	 sonrrcConnectionReconfigurationRequest;
			struct SonRRCConnectionReconfigurationRequest__criticalExtensions__criticalExtensionsFuture {
			} criticalExtensionsFuture;
		} choice;
	} criticalExtensions;
} SonRRCConnectionReconfigurationRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReconfigurationRequest;

/******  SonRRCConnectionReconfigurationRequest Definition End *****/


/******  FixedOccupiedPerRadioFrame Definition Start *****/

/* Forward declarations */
struct Parameter;

/* FixedOccupiedPerRadioFrame */
typedef struct FixedOccupiedPerRadioFrame {
	long	 metric;
	struct Parameter	*parameter	/* OPTIONAL */;
	OCTET_STRING_t	 nodeSN;
} FixedOccupiedPerRadioFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FixedOccupiedPerRadioFrame;

/******  FixedOccupiedPerRadioFrame Definition End *****/

/******  OccupiedPerRadioFrame Definition Start *****/

/* Forward declarations */
struct FixedOccupiedPerRadioFrame;
struct DynamicOccupiedPerRadioFrame;

/* OccupiedPerRadioFrame */
typedef struct OccupiedPerRadioFrame {
	struct FixedOccupiedPerRadioFrame	*fixedOccupiedPerRadioFrame	/* OPTIONAL */;
	struct DynamicOccupiedPerRadioFrame	*dynamicOccupiedPerRadioFrame	/* OPTIONAL */;
} OccupiedPerRadioFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OccupiedPerRadioFrame;

/******  OccupiedPerRadioFrame Definition End *****/

/******  SON-BCCH-BCH-MessageType Definition Start *****/

/* SON-BCCH-BCH-MessageType */
typedef SonMasterInformationBlock_t	 SON_BCCH_BCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SON_BCCH_BCH_MessageType;
per_type_decoder_f SON_BCCH_BCH_MessageType_decode_uper;
per_type_encoder_f SON_BCCH_BCH_MessageType_encode_uper;

/******  SON-BCCH-BCH-MessageType Definition End *****/


/******  SON-BCCH-BCH-Message Definition Start *****/

/* SON-BCCH-BCH-Message */
typedef struct SON_BCCH_BCH_Message {
	SON_BCCH_BCH_MessageType_t	 message;
} SON_BCCH_BCH_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SON_BCCH_BCH_Message;

/******  SON-BCCH-BCH-Message Definition End *****/


/******  Parameter Definition Start *****/

/* Parameter */
typedef struct Parameter {
	long	 dataArrivalRate;
} Parameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Parameter;

/******  Parameter Definition End *****/


/******  OccupiedRadioFrameList Definition Start *****/

/* Forward declarations */
struct OccupiedPerRadioFrame;

/* OccupiedRadioFrameList */
typedef struct OccupiedRadioFrameList {
	A_SEQUENCE_OF(struct OccupiedPerRadioFrame) list;
} OccupiedRadioFrameList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OccupiedRadioFrameList;

/******  OccupiedRadioFrameList Definition End *****/


/******  DynamicOccupiedPerRadioFrame Definition Start *****/

/* Dependencies */
typedef enum DynamicOccupiedPerRadioFrame__conflictIndication {
	DynamicOccupiedPerRadioFrame__conflictIndication_false	= 0,
	DynamicOccupiedPerRadioFrame__conflictIndication_true	= 1
} e_DynamicOccupiedPerRadioFrame__conflictIndication;

/* DynamicOccupiedPerRadioFrame */
typedef struct DynamicOccupiedPerRadioFrame {
	long	 nodeId;
	long	 conflictIndication;
} DynamicOccupiedPerRadioFrame_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_conflictIndication_142;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DynamicOccupiedPerRadioFrame;

/******  DynamicOccupiedPerRadioFrame Definition End *****/

#ifdef __cplusplus
} // end of #ifdef __cplusplus
#endif

#endif // end of #ifdef SON_RRC_DEFINITIONS