import os
import re

# Used to merge rrc header files.
# Set the input and output file names
input_file = "AllNRHdr.h"
output_file = "NR-RRC-Definitions.h"
header_location = "E:\\GitCode\\NRRRCASN1Debug\\NEW"
target_path = "E:\\GitCode\\NRRRCASN1Debug\\NEW"

# Used to merge lpp header files.
# input_file = "LPPAllHeaders.h"
# output_file = "LPP-PDU-Definitions.h"
# header_location = "LPPHeaderFolder"

# Set to keep track of expanded header files
expanded_headers = set()

# Function to expand header files recursively
def expand_header(header_file):
    global expanded_headers

    # Check if header file has already been expanded
    if header_file in expanded_headers:
        return ""
    else:
        # Add header file to set of expanded headers
        expanded_headers.add(header_file)
        print(f"Add header file to expanded list: {header_file}")


    # Check if header file exists
    if not os.path.isfile(header_file):
        print(f"{header_file} Not exist!")
        return ""

    print(f"Start output {header_file}")
    # Open the header file and read its contents
    with open(header_file, "r") as f_header:
        header_text = f_header.read()

        # Find all #include statements in the header text
        include_regex = r'#include\s*\"(.+\.h)\"'
        matches = re.findall(include_regex, header_text)

        # Recursively expand any included header files
        for match in matches:
            included_header = match
            included_text = expand_header(included_header)
            header_text = header_text.replace("#include \"{}\"".format(included_header), included_text)

        # Remove all lines containing #ifdef, #define, and #endif
        header_text = re.sub(r'^.*#(ifndef|ifdef|define|endif).*\n?', '', header_text, flags=re.MULTILINE)
        header_text = re.sub(r'\n\s*\n', '\n\n', header_text, flags=re.MULTILINE)

        print(f"End output {header_file}")
        # Return the expanded header text
        # return "\n/* Start Definition of {}  */\n\n".format(header_file) + header_text + "/* End Definition of {} */\n".format(header_file)
        return header_text


def generate_header_guard(file_name):
    if file_name is None:
        print("ERROR:output file is not specific.")
    if file_name == "":
        print("ERROR:output file is empty.")

    name_no_sufix = file_name.split('.')[0]
    guard_name = name_no_sufix.upper()
    return guard_name.replace('-', '_')


def main():
    os.chdir(target_path)
    # Open the input and output files
    with open(input_file, "r") as f_in, open(output_file, "w") as f_out:
        current_workspace = os.getcwd()
        # Read the entire input file
        input_text = f_in.read()

        # Find all #include statements in the input text
        include_regex = r'\s*(.+\.h)'
        matches = re.findall(include_regex, input_text)

        # provided input file contain include file, output the preamble of outputfile.
        if len(matches) > 0:
            # 1. Add preamble
            preamble = "/*\n * Generated by ESWINCOMPUTING easn1c \n * And merged all header files by HeaderFileAllInOne.py.\n*/\n\n"
            f_out.write(preamble)

            # 2. Add header guard
            guard_name = generate_header_guard(output_file)
            header_guard = f"#ifndef\t_{guard_name}_H_\n#define\t_{guard_name}_H_\n\n"
            f_out.write(header_guard)

            include_header = "#include \"asn1c_support_lib.h\"\n\n"
            f_out.write(include_header)

            # Add extern "C" wrapper
            wrapper_start = "\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n"
            f_out.write(wrapper_start)


        # Write the original input text to the output file
        # f_out.write(input_text)

        os.chdir(header_location)

        # For each match, expand the corresponding header file and write it to the output file
        for match in matches:
            header_file = match
            print(f"expand header file:{header_file}")
            expanded_text = expand_header(header_file)
            if not expanded_text:
                input_text = input_text.replace("#include \"{}\"".format(header_file), "")
            else:
                input_text = input_text.replace("#include \"{}\"".format(header_file), expanded_text)
                f_out.write(expanded_text)

        # Add extern "C" wrapper end
        wrapper_end = "\n#ifdef __cplusplus\n} // end of #ifdef __cplusplus\n#endif\n"
        f_out.write(wrapper_end)

        # Add guard matched guard end.
        f_out.write(f"\n#endif // end of #ifdef {guard_name}")

        # Remove all lines containing #ifdef, #define, and #endif
        #input_text = re.sub(r'^.*#(ifdef|define|endif).*\n?', '', input_text, flags=re.MULTILINE)

        # Write the final expanded input text (with #ifdef, #define, and #endif lines removed) to the output file
        #f_out.write(input_text)


if __name__ == '__main__':
    main()