/*
 * Generated by easn1c-V1.1 (liuyongqi@eswincomputing.com)
 * From ASN.1 module "SON-RRC-Definitions"
 * 	found in "uav_rrc.asn1"
 * 	`easn1c -Wdebug-compiler -fcompound-names -fincludes-quoted -fno-include-deps -gen-PER -pdu=auto`
 */

#include "SON-RRC-Definitions.h"


/******  SON-BCCH-BCH-Message Implement Start *****/
static asn_TYPE_member_t asn_MBR_SON_BCCH_BCH_Message_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_BCH_Message, message),
		&asn_DEF_SON_BCCH_BCH_MessageType,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"message"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SON_BCCH_BCH_Message_specs_1 = {
	sizeof(struct SON_BCCH_BCH_Message),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SON_BCCH_BCH_Message = {
#ifdef _ASN1_DEBUG_MODE_
	"SON-BCCH-BCH-Message",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SON_BCCH_BCH_Message_1,
	1,	/* Elements count */
	&asn_SPC_SON_BCCH_BCH_Message_specs_1	/* Additional specs */
};

/******  SON-BCCH-BCH-Message Implement End *****/

/******  SON-BCCH-BCH-MessageType Implement Start *****/
/*
 * This type is implemented using SonMasterInformationBlock,
 * so here we adjust the DEF accordingly.
 */
static void
SON_BCCH_BCH_MessageType_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_SonMasterInformationBlock.uper_decoder;
	td->uper_encoder   = asn_DEF_SonMasterInformationBlock.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_SonMasterInformationBlock.per_constraints;
	td->elements       = asn_DEF_SonMasterInformationBlock.elements;
	td->elements_count = asn_DEF_SonMasterInformationBlock.elements_count;
	td->specifics      = asn_DEF_SonMasterInformationBlock.specifics;
}

asn_dec_rval_t
SON_BCCH_BCH_MessageType_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	SON_BCCH_BCH_MessageType_3_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
SON_BCCH_BCH_MessageType_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	SON_BCCH_BCH_MessageType_3_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

asn_TYPE_descriptor_t asn_DEF_SON_BCCH_BCH_MessageType = {
#ifdef _ASN1_DEBUG_MODE_
	"SON-BCCH-BCH-MessageType",
#endif
	SON_BCCH_BCH_MessageType_decode_uper,
	SON_BCCH_BCH_MessageType_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};

/******  SON-BCCH-BCH-MessageType Implement End *****/

/******  SON-BCCH-TCH-Message Implement Start *****/
static asn_TYPE_member_t asn_MBR_SON_BCCH_TCH_Message_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_Message, message),
		&asn_DEF_SON_BCCH_TCH_MessageType,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"message"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SON_BCCH_TCH_Message_specs_4 = {
	sizeof(struct SON_BCCH_TCH_Message),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SON_BCCH_TCH_Message = {
#ifdef _ASN1_DEBUG_MODE_
	"SON-BCCH-TCH-Message",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SON_BCCH_TCH_Message_4,
	1,	/* Elements count */
	&asn_SPC_SON_BCCH_TCH_Message_specs_4	/* Additional specs */
};

/******  SON-BCCH-TCH-Message Implement End *****/

/******  SON-BCCH-TCH-MessageType Implement Start *****/
static asn_per_constraints_t asn_PER_type_c1_constr_7 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_type_SON_BCCH_TCH_MessageType_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_c1_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.sonsystemInformationBlockType1),
		&asn_DEF_SonSystemInformationBlockType1,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonsystemInformationBlockType1"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.sonsystemInformationBlockType2),
		&asn_DEF_SonSystemInformationBlockType2,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonsystemInformationBlockType2"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.spare5),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare5"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.spare4),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare4"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.spare3),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare3"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.spare2),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare2"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType__c1, choice.spare1),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare1"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_c1_specs_7 = {
	sizeof(struct SON_BCCH_TCH_MessageType__c1),
	offsetof(struct SON_BCCH_TCH_MessageType__c1, present),
	sizeof(((struct SON_BCCH_TCH_MessageType__c1 *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_c1_7 = {
#ifdef _ASN1_DEBUG_MODE_
	"c1",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_c1_constr_7,
	asn_MBR_c1_7,
	7,	/* Elements count */
	&asn_SPC_c1_specs_7	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_messageClassExtension_specs_15 = {
	sizeof(struct SON_BCCH_TCH_MessageType__messageClassExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageClassExtension_15 = {
#ifdef _ASN1_DEBUG_MODE_
	"messageClassExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_messageClassExtension_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SON_BCCH_TCH_MessageType_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType, choice.c1),
		&asn_DEF_c1_7,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"c1"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_BCCH_TCH_MessageType, choice.messageClassExtension),
		&asn_DEF_messageClassExtension_15,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"messageClassExtension"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_SON_BCCH_TCH_MessageType_specs_6 = {
	sizeof(struct SON_BCCH_TCH_MessageType),
	offsetof(struct SON_BCCH_TCH_MessageType, present),
	sizeof(((struct SON_BCCH_TCH_MessageType *)0)->present),
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SON_BCCH_TCH_MessageType = {
#ifdef _ASN1_DEBUG_MODE_
	"SON-BCCH-TCH-MessageType",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_SON_BCCH_TCH_MessageType_constr_6,
	asn_MBR_SON_BCCH_TCH_MessageType_6,
	2,	/* Elements count */
	&asn_SPC_SON_BCCH_TCH_MessageType_specs_6	/* Additional specs */
};

/******  SON-BCCH-TCH-MessageType Implement End *****/

/******  SON-DCCH-TCH-Message Implement Start *****/
static asn_TYPE_member_t asn_MBR_SON_DCCH_TCH_Message_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_Message, message),
		&asn_DEF_SON_DCCH_TCH_MessageType,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"message"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SON_DCCH_TCH_Message_specs_16 = {
	sizeof(struct SON_DCCH_TCH_Message),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SON_DCCH_TCH_Message = {
#ifdef _ASN1_DEBUG_MODE_
	"SON-DCCH-TCH-Message",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SON_DCCH_TCH_Message_16,
	1,	/* Elements count */
	&asn_SPC_SON_DCCH_TCH_Message_specs_16	/* Additional specs */
};

/******  SON-DCCH-TCH-Message Implement End *****/

/******  SON-DCCH-TCH-MessageType Implement Start *****/
static asn_per_constraints_t asn_PER_type_c1_constr_19 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_type_SON_DCCH_TCH_MessageType_constr_18 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_c1_19[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.sonRrcConnectionRequest),
		&asn_DEF_SonRRCConnectionRequest,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonRrcConnectionRequest"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.sonRrcConnectionReject),
		&asn_DEF_SonRRCConnectionReject,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonRrcConnectionReject"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.sonRrcConnectionConfirm),
		&asn_DEF_SonRRCConnectionConfirm,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonRrcConnectionConfirm"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.spare5),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare5"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.spare4),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare4"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.spare3),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare3"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.spare2),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare2"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType__c1, choice.spare1),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare1"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_c1_specs_19 = {
	sizeof(struct SON_DCCH_TCH_MessageType__c1),
	offsetof(struct SON_DCCH_TCH_MessageType__c1, present),
	sizeof(((struct SON_DCCH_TCH_MessageType__c1 *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_c1_19 = {
#ifdef _ASN1_DEBUG_MODE_
	"c1",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_c1_constr_19,
	asn_MBR_c1_19,
	8,	/* Elements count */
	&asn_SPC_c1_specs_19	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_messageClassExtension_specs_28 = {
	sizeof(struct SON_DCCH_TCH_MessageType__messageClassExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageClassExtension_28 = {
#ifdef _ASN1_DEBUG_MODE_
	"messageClassExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_messageClassExtension_specs_28	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SON_DCCH_TCH_MessageType_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType, choice.c1),
		&asn_DEF_c1_19,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"c1"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SON_DCCH_TCH_MessageType, choice.messageClassExtension),
		&asn_DEF_messageClassExtension_28,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"messageClassExtension"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_SON_DCCH_TCH_MessageType_specs_18 = {
	sizeof(struct SON_DCCH_TCH_MessageType),
	offsetof(struct SON_DCCH_TCH_MessageType, present),
	sizeof(((struct SON_DCCH_TCH_MessageType *)0)->present),
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SON_DCCH_TCH_MessageType = {
#ifdef _ASN1_DEBUG_MODE_
	"SON-DCCH-TCH-MessageType",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_SON_DCCH_TCH_MessageType_constr_18,
	asn_MBR_SON_DCCH_TCH_MessageType_18,
	2,	/* Elements count */
	&asn_SPC_SON_DCCH_TCH_MessageType_specs_18	/* Additional specs */
};

/******  SON-DCCH-TCH-MessageType Implement End *****/

/******  SonMasterInformationBlock Implement Start *****/
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
bandwidth_30_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
bandwidth_30_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	bandwidth_30_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
bandwidth_30_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	bandwidth_30_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
transmissionMode_38_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
transmissionMode_38_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	transmissionMode_38_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
transmissionMode_38_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	transmissionMode_38_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
antennaPortNum_46_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
antennaPortNum_46_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	antennaPortNum_46_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
antennaPortNum_46_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	antennaPortNum_46_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_bandwidth_constr_30 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_type_transmissionMode_constr_38 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_type_antennaPortNum_constr_46 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_systemFrameNumber_constr_37 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  10,  10 }	/* (SIZE(10..10)) */
};
static asn_per_constraints_t asn_PER_memb_version_constr_43 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */
};
static asn_per_constraints_t asn_PER_memb_currntNodeId_constr_44 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_totalNodeNum_constr_45 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (1..32) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_txPower_constr_50 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7, -40,  50 }	/* (-40..50) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_macI_constr_51 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  10,  10 }	/* (SIZE(10..10)) */
};
static asn_per_constraints_t asn_PER_memb_sonId_constr_52 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static const asn_INTEGER_enum_map_t asn_MAP_bandwidth_value2enum_30[] = {
	{ 0 },
	{ 1 },
	{ 2 },
	{ 3 },
	{ 4 },
	{ 5 }
};
static const uint8_t asn_MAP_bandwidth_enum2value_30[] = {
	5,	/* n100(5) */
	1,	/* n15(1) */
	2,	/* n25(2) */
	3,	/* n50(3) */
	0,	/* n6(0) */
	4	/* n75(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_bandwidth_specs_30 = {
	asn_MAP_bandwidth_value2enum_30,	/* "tag" => N; sorted by tag */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_bandwidth_30 = {
#ifdef _ASN1_DEBUG_MODE_
	"bandwidth",
#endif
	bandwidth_30_decode_uper,
	bandwidth_30_encode_uper,
	&asn_PER_type_bandwidth_constr_30,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_bandwidth_specs_30	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_transmissionMode_value2enum_38[] = {
	{ 0 },
	{ 1 },
	{ 2 },
	{ 3 }
};
static const uint8_t asn_MAP_transmissionMode_enum2value_38[] = {
	0,	/* tm0(0) */
	1,	/* tm1(1) */
	2,	/* tm2(2) */
	3	/* tm3(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_transmissionMode_specs_38 = {
	asn_MAP_transmissionMode_value2enum_38,	/* "tag" => N; sorted by tag */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transmissionMode_38 = {
#ifdef _ASN1_DEBUG_MODE_
	"transmissionMode",
#endif
	transmissionMode_38_decode_uper,
	transmissionMode_38_encode_uper,
	&asn_PER_type_transmissionMode_constr_38,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_transmissionMode_specs_38	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_antennaPortNum_value2enum_46[] = {
	{ 0 },
	{ 1 },
	{ 2 }
};
static const uint8_t asn_MAP_antennaPortNum_enum2value_46[] = {
	0,	/* ap1(0) */
	1,	/* ap2(1) */
	2	/* ap4(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_antennaPortNum_specs_46 = {
	asn_MAP_antennaPortNum_value2enum_46,	/* "tag" => N; sorted by tag */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_antennaPortNum_46 = {
#ifdef _ASN1_DEBUG_MODE_
	"antennaPortNum",
#endif
	antennaPortNum_46_decode_uper,
	antennaPortNum_46_encode_uper,
	&asn_PER_type_antennaPortNum_constr_46,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_antennaPortNum_specs_46	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_53 = {
	sizeof(struct SonMasterInformationBlock__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_53 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_53	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonMasterInformationBlock_29[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, bandwidth),
		&asn_DEF_bandwidth_30,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"bandwidth"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, systemFrameNumber),
		&asn_DEF_BIT_STRING,
		&asn_PER_memb_systemFrameNumber_constr_37,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"systemFrameNumber"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, transmissionMode),
		&asn_DEF_transmissionMode_38,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"transmissionMode"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, version),
		&asn_DEF_BIT_STRING,
		&asn_PER_memb_version_constr_43,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"version"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, currntNodeId),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_currntNodeId_constr_44,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"currntNodeId"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, totalNodeNum),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_totalNodeNum_constr_45,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"totalNodeNum"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, antennaPortNum),
		&asn_DEF_antennaPortNum_46,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"antennaPortNum"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, txPower),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_txPower_constr_50,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"txPower"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, macI),
		&asn_DEF_BIT_STRING,
		&asn_PER_memb_macI_constr_51,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"macI"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonMasterInformationBlock, sonId),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_sonId_constr_52,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonId"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonMasterInformationBlock, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_53,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonMasterInformationBlock_oms_29[] = { 10 };
static asn_SEQUENCE_specifics_t asn_SPC_SonMasterInformationBlock_specs_29 = {
	sizeof(struct SonMasterInformationBlock),
	asn_MAP_SonMasterInformationBlock_oms_29,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonMasterInformationBlock = {
#ifdef _ASN1_DEBUG_MODE_
	"SonMasterInformationBlock",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonMasterInformationBlock_29,
	11,	/* Elements count */
	&asn_SPC_SonMasterInformationBlock_specs_29	/* Additional specs */
};

/******  SonMasterInformationBlock Implement End *****/

/******  SonRRCConnectionConfirm Implement Start *****/
static asn_per_constraints_t asn_PER_type_c1_constr_56 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_55 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_c1_56[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm__criticalExtensions__c1, choice.rrcConnectionConfirm),
		&asn_DEF_SonRRCConnectionConfirm_IEs,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"rrcConnectionConfirm"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm__criticalExtensions__c1, choice.spare),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_c1_specs_56 = {
	sizeof(struct SonRRCConnectionConfirm__criticalExtensions__c1),
	offsetof(struct SonRRCConnectionConfirm__criticalExtensions__c1, present),
	sizeof(((struct SonRRCConnectionConfirm__criticalExtensions__c1 *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_c1_56 = {
#ifdef _ASN1_DEBUG_MODE_
	"c1",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_c1_constr_56,
	asn_MBR_c1_56,
	2,	/* Elements count */
	&asn_SPC_c1_specs_56	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensionsFuture_specs_59 = {
	sizeof(struct SonRRCConnectionConfirm__criticalExtensions__criticalExtensionsFuture),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensionsFuture_59 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensionsFuture",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_criticalExtensionsFuture_specs_59	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_55[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm__criticalExtensions, choice.c1),
		&asn_DEF_c1_56,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"c1"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm__criticalExtensions, choice.criticalExtensionsFuture),
		&asn_DEF_criticalExtensionsFuture_59,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensionsFuture"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_55 = {
	sizeof(struct SonRRCConnectionConfirm__criticalExtensions),
	offsetof(struct SonRRCConnectionConfirm__criticalExtensions, present),
	sizeof(((struct SonRRCConnectionConfirm__criticalExtensions *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_55 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensions",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_criticalExtensions_constr_55,
	asn_MBR_criticalExtensions_55,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_55	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionConfirm_54[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm, criticalExtensions),
		&asn_DEF_criticalExtensions_55,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensions"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionConfirm_specs_54 = {
	sizeof(struct SonRRCConnectionConfirm),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionConfirm = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionConfirm",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionConfirm_54,
	1,	/* Elements count */
	&asn_SPC_SonRRCConnectionConfirm_specs_54	/* Additional specs */
};

/******  SonRRCConnectionConfirm Implement End *****/

/******  SonRRCConnectionConfirm-IEs Implement Start *****/
static asn_per_constraints_t asn_PER_memb_occupiedRF_constr_61 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_64 = {
	sizeof(struct SonRRCConnectionConfirm_IEs__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_64 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_64	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionConfirm_IEs_60[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm_IEs, occupiedRF),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_occupiedRF_constr_61,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"occupiedRF"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm_IEs, accessingNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"accessingNodeAddress"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionConfirm_IEs, accessedNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"accessedNodeAddress"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonRRCConnectionConfirm_IEs, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_64,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonRRCConnectionConfirm_IEs_oms_60[] = { 3 };
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionConfirm_IEs_specs_60 = {
	sizeof(struct SonRRCConnectionConfirm_IEs),
	asn_MAP_SonRRCConnectionConfirm_IEs_oms_60,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionConfirm_IEs = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionConfirm-IEs",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionConfirm_IEs_60,
	4,	/* Elements count */
	&asn_SPC_SonRRCConnectionConfirm_IEs_specs_60	/* Additional specs */
};

/******  SonRRCConnectionConfirm-IEs Implement End *****/

/******  SonRRCConnectionReject Implement Start *****/
static asn_per_constraints_t asn_PER_type_c1_constr_67 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_66 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_c1_67[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject__criticalExtensions__c1, choice.rrcConnectionReject),
		&asn_DEF_SonRRCConnectionReject_IEs,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"rrcConnectionReject"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject__criticalExtensions__c1, choice.spare),
		&asn_DEF_NULL,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"spare"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_c1_specs_67 = {
	sizeof(struct SonRRCConnectionReject__criticalExtensions__c1),
	offsetof(struct SonRRCConnectionReject__criticalExtensions__c1, present),
	sizeof(((struct SonRRCConnectionReject__criticalExtensions__c1 *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_c1_67 = {
#ifdef _ASN1_DEBUG_MODE_
	"c1",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_c1_constr_67,
	asn_MBR_c1_67,
	2,	/* Elements count */
	&asn_SPC_c1_specs_67	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensionsFuture_specs_70 = {
	sizeof(struct SonRRCConnectionReject__criticalExtensions__criticalExtensionsFuture),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensionsFuture_70 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensionsFuture",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_criticalExtensionsFuture_specs_70	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_66[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject__criticalExtensions, choice.c1),
		&asn_DEF_c1_67,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"c1"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject__criticalExtensions, choice.criticalExtensionsFuture),
		&asn_DEF_criticalExtensionsFuture_70,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensionsFuture"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_66 = {
	sizeof(struct SonRRCConnectionReject__criticalExtensions),
	offsetof(struct SonRRCConnectionReject__criticalExtensions, present),
	sizeof(((struct SonRRCConnectionReject__criticalExtensions *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_66 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensions",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_criticalExtensions_constr_66,
	asn_MBR_criticalExtensions_66,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_66	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionReject_65[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject, criticalExtensions),
		&asn_DEF_criticalExtensions_66,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensions"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionReject_specs_65 = {
	sizeof(struct SonRRCConnectionReject),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReject = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionReject",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionReject_65,
	1,	/* Elements count */
	&asn_SPC_SonRRCConnectionReject_specs_65	/* Additional specs */
};

/******  SonRRCConnectionReject Implement End *****/

/******  SonRRCConnectionReject-IEs Implement Start *****/
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
rejectCause_74_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
rejectCause_74_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	rejectCause_74_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
rejectCause_74_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	rejectCause_74_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_rejectCause_constr_74 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static const asn_INTEGER_enum_map_t asn_MAP_rejectCause_value2enum_74[] = {
	{ 0 },
	{ 1 },
	{ 2 },
	{ 3 },
	{ 4 },
	{ 5 },
	{ 6 },
	{ 7 }
};
static const uint8_t asn_MAP_rejectCause_enum2value_74[] = {
	0,	/* congestion(0) */
	7,	/* spare1(7) */
	6,	/* spare2(6) */
	5,	/* spare3(5) */
	4,	/* spare4(4) */
	3,	/* spare5(3) */
	2,	/* spare6(2) */
	1	/* spare7(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_rejectCause_specs_74 = {
	asn_MAP_rejectCause_value2enum_74,	/* "tag" => N; sorted by tag */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rejectCause_74 = {
#ifdef _ASN1_DEBUG_MODE_
	"rejectCause",
#endif
	rejectCause_74_decode_uper,
	rejectCause_74_encode_uper,
	&asn_PER_type_rejectCause_constr_74,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rejectCause_specs_74	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_83 = {
	sizeof(struct SonRRCConnectionReject_IEs__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_83 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_83	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionReject_IEs_71[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject_IEs, accessingNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"accessingNodeAddress"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject_IEs, accessedNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"accessedNodeAddress"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReject_IEs, rejectCause),
		&asn_DEF_rejectCause_74,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"rejectCause"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonRRCConnectionReject_IEs, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_83,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonRRCConnectionReject_IEs_oms_71[] = { 3 };
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionReject_IEs_specs_71 = {
	sizeof(struct SonRRCConnectionReject_IEs),
	asn_MAP_SonRRCConnectionReject_IEs_oms_71,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReject_IEs = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionReject-IEs",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionReject_IEs_71,
	4,	/* Elements count */
	&asn_SPC_SonRRCConnectionReject_IEs_specs_71	/* Additional specs */
};

/******  SonRRCConnectionReject-IEs Implement End *****/

/******  SonRRCConnectionRequest Implement Start *****/
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_85 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensionsFuture_specs_87 = {
	sizeof(struct SonRRCConnectionRequest__criticalExtensions__criticalExtensionsFuture),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensionsFuture_87 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensionsFuture",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_criticalExtensionsFuture_specs_87	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_85[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionRequest__criticalExtensions, choice.sonrrcConnectionRequest),
		&asn_DEF_SonRRCConnectionRequest_IEs,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonrrcConnectionRequest"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionRequest__criticalExtensions, choice.criticalExtensionsFuture),
		&asn_DEF_criticalExtensionsFuture_87,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensionsFuture"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_85 = {
	sizeof(struct SonRRCConnectionRequest__criticalExtensions),
	offsetof(struct SonRRCConnectionRequest__criticalExtensions, present),
	sizeof(((struct SonRRCConnectionRequest__criticalExtensions *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_85 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensions",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_criticalExtensions_constr_85,
	asn_MBR_criticalExtensions_85,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_85	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionRequest_84[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionRequest, criticalExtensions),
		&asn_DEF_criticalExtensions_85,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensions"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionRequest_specs_84 = {
	sizeof(struct SonRRCConnectionRequest),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionRequest = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionRequest",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionRequest_84,
	1,	/* Elements count */
	&asn_SPC_SonRRCConnectionRequest_specs_84	/* Additional specs */
};

/******  SonRRCConnectionRequest Implement End *****/

/******  SonRRCConnectionRequest-IEs Implement Start *****/
static asn_per_constraints_t asn_PER_memb_pre_occupiedRF_constr_89 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_92 = {
	sizeof(struct SonRRCConnectionRequest_IEs__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_92 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_92	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionRequest_IEs_88[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionRequest_IEs, pre_occupiedRF),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_pre_occupiedRF_constr_89,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"pre-occupiedRF"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionRequest_IEs, accessingNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"accessingNodeAddress"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionRequest_IEs, accessedNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"accessedNodeAddress"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonRRCConnectionRequest_IEs, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_92,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonRRCConnectionRequest_IEs_oms_88[] = { 3 };
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionRequest_IEs_specs_88 = {
	sizeof(struct SonRRCConnectionRequest_IEs),
	asn_MAP_SonRRCConnectionRequest_IEs_oms_88,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionRequest_IEs = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionRequest-IEs",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionRequest_IEs_88,
	4,	/* Elements count */
	&asn_SPC_SonRRCConnectionRequest_IEs_specs_88	/* Additional specs */
};

/******  SonRRCConnectionRequest-IEs Implement End *****/

/******  SonRRCConnectionReconfigurationRequest Implement Start *****/
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_94 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensionsFuture_specs_96 = {
	sizeof(struct SonRRCConnectionReconfigurationRequest__criticalExtensions__criticalExtensionsFuture),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensionsFuture_96 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensionsFuture",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_criticalExtensionsFuture_specs_96	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_94[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest__criticalExtensions, choice.sonrrcConnectionReconfigurationRequest),
		&asn_DEF_SonRRCConnectionReconfigurationRequest_IEs,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"sonrrcConnectionReconfigurationRequest"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest__criticalExtensions, choice.criticalExtensionsFuture),
		&asn_DEF_criticalExtensionsFuture_96,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensionsFuture"
#endif
	},
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_94 = {
	sizeof(struct SonRRCConnectionReconfigurationRequest__criticalExtensions),
	offsetof(struct SonRRCConnectionReconfigurationRequest__criticalExtensions, present),
	sizeof(((struct SonRRCConnectionReconfigurationRequest__criticalExtensions *)0)->present),
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_94 = {
#ifdef _ASN1_DEBUG_MODE_
	"criticalExtensions",
#endif
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	&asn_PER_type_criticalExtensions_constr_94,
	asn_MBR_criticalExtensions_94,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_94	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionReconfigurationRequest_93[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest, criticalExtensions),
		&asn_DEF_criticalExtensions_94,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"criticalExtensions"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionReconfigurationRequest_specs_93 = {
	sizeof(struct SonRRCConnectionReconfigurationRequest),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReconfigurationRequest = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionReconfigurationRequest",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionReconfigurationRequest_93,
	1,	/* Elements count */
	&asn_SPC_SonRRCConnectionReconfigurationRequest_specs_93	/* Additional specs */
};

/******  SonRRCConnectionReconfigurationRequest Implement End *****/

/******  SonRRCConnectionReconfigurationRequest-IEs Implement Start *****/
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
bandwidth_99_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
bandwidth_99_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	bandwidth_99_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
bandwidth_99_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	bandwidth_99_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_bandwidth_constr_99 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_freqInfo_constr_98 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_physCellId_constr_106 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  503 }	/* (0..503) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static const asn_INTEGER_enum_map_t asn_MAP_bandwidth_value2enum_99[] = {
	{ 0 },
	{ 1 },
	{ 2 },
	{ 3 },
	{ 4 },
	{ 5 }
};
static const uint8_t asn_MAP_bandwidth_enum2value_99[] = {
	5,	/* n100(5) */
	1,	/* n15(1) */
	2,	/* n25(2) */
	3,	/* n50(3) */
	0,	/* n6(0) */
	4	/* n75(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_bandwidth_specs_99 = {
	asn_MAP_bandwidth_value2enum_99,	/* "tag" => N; sorted by tag */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_bandwidth_99 = {
#ifdef _ASN1_DEBUG_MODE_
	"bandwidth",
#endif
	bandwidth_99_decode_uper,
	bandwidth_99_encode_uper,
	&asn_PER_type_bandwidth_constr_99,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_bandwidth_specs_99	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_108 = {
	sizeof(struct SonRRCConnectionReconfigurationRequest_IEs__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_108 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_108	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonRRCConnectionReconfigurationRequest_IEs_97[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest_IEs, freqInfo),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_freqInfo_constr_98,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"freqInfo"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest_IEs, bandwidth),
		&asn_DEF_bandwidth_99,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"bandwidth"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest_IEs, physCellId),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_physCellId_constr_106,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"physCellId"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonRRCConnectionReconfigurationRequest_IEs, activeTime),
		&asn_DEF_ActiveTime,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"activeTime"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonRRCConnectionReconfigurationRequest_IEs, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_108,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonRRCConnectionReconfigurationRequest_IEs_oms_97[] = { 4 };
static asn_SEQUENCE_specifics_t asn_SPC_SonRRCConnectionReconfigurationRequest_IEs_specs_97 = {
	sizeof(struct SonRRCConnectionReconfigurationRequest_IEs),
	asn_MAP_SonRRCConnectionReconfigurationRequest_IEs_oms_97,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonRRCConnectionReconfigurationRequest_IEs = {
#ifdef _ASN1_DEBUG_MODE_
	"SonRRCConnectionReconfigurationRequest-IEs",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonRRCConnectionReconfigurationRequest_IEs_97,
	5,	/* Elements count */
	&asn_SPC_SonRRCConnectionReconfigurationRequest_IEs_specs_97	/* Additional specs */
};

/******  SonRRCConnectionReconfigurationRequest-IEs Implement End *****/

/******  SonSystemInformationBlockType1 Implement Start *****/
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
messageSegmentType_111_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
messageSegmentType_111_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	messageSegmentType_111_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
messageSegmentType_111_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	messageSegmentType_111_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_messageSegmentType_constr_111 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_messageSequenceNumber_constr_110 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_messageSegmentNumber_constr_114 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  63 }	/* (0..63) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static const asn_INTEGER_enum_map_t asn_MAP_messageSegmentType_value2enum_111[] = {
	{ 0 },
	{ 1 }
};
static const uint8_t asn_MAP_messageSegmentType_enum2value_111[] = {
	1,	/* lastSegment(1) */
	0	/* notLastSegment(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_messageSegmentType_specs_111 = {
	asn_MAP_messageSegmentType_value2enum_111,	/* "tag" => N; sorted by tag */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageSegmentType_111 = {
#ifdef _ASN1_DEBUG_MODE_
	"messageSegmentType",
#endif
	messageSegmentType_111_decode_uper,
	messageSegmentType_111_encode_uper,
	&asn_PER_type_messageSegmentType_constr_111,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_messageSegmentType_specs_111	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_116 = {
	sizeof(struct SonSystemInformationBlockType1__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_116 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_116	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonSystemInformationBlockType1_109[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType1, messageSequenceNumber),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_messageSequenceNumber_constr_110,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"messageSequenceNumber"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType1, messageSegmentType),
		&asn_DEF_messageSegmentType_111,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"messageSegmentType"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType1, messageSegmentNumber),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_messageSegmentNumber_constr_114,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"messageSegmentNumber"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType1, nodeRouteInformation),
		&asn_DEF_NodeRouteInformation,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nodeRouteInformation"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonSystemInformationBlockType1, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_116,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonSystemInformationBlockType1_oms_109[] = { 4 };
static asn_SEQUENCE_specifics_t asn_SPC_SonSystemInformationBlockType1_specs_109 = {
	sizeof(struct SonSystemInformationBlockType1),
	asn_MAP_SonSystemInformationBlockType1_oms_109,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonSystemInformationBlockType1 = {
#ifdef _ASN1_DEBUG_MODE_
	"SonSystemInformationBlockType1",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonSystemInformationBlockType1_109,
	5,	/* Elements count */
	&asn_SPC_SonSystemInformationBlockType1_specs_109	/* Additional specs */
};

/******  SonSystemInformationBlockType1 Implement End *****/

/******  SonSystemInformationBlockType2 Implement Start *****/
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
currentNodeLeaveIndication_121_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
currentNodeLeaveIndication_121_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	currentNodeLeaveIndication_121_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
currentNodeLeaveIndication_121_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	currentNodeLeaveIndication_121_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_currentNodeLeaveIndication_constr_121 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_ssfnCycle_constr_118 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_currentNodeId_constr_119 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_messageSequenceNumber_constr_120 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static const asn_INTEGER_enum_map_t asn_MAP_currentNodeLeaveIndication_value2enum_121[] = {
	{ 0 },
	{ 1 }
};
static const uint8_t asn_MAP_currentNodeLeaveIndication_enum2value_121[] = {
	0,	/* false(0) */
	1	/* true(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_currentNodeLeaveIndication_specs_121 = {
	asn_MAP_currentNodeLeaveIndication_value2enum_121,	/* "tag" => N; sorted by tag */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_currentNodeLeaveIndication_121 = {
#ifdef _ASN1_DEBUG_MODE_
	"currentNodeLeaveIndication",
#endif
	currentNodeLeaveIndication_121_decode_uper,
	currentNodeLeaveIndication_121_encode_uper,
	&asn_PER_type_currentNodeLeaveIndication_constr_121,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_currentNodeLeaveIndication_specs_121	/* Additional specs */
};

static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_128 = {
	sizeof(struct SonSystemInformationBlockType2__nonCriticalExtension),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_128 = {
#ifdef _ASN1_DEBUG_MODE_
	"nonCriticalExtension",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_128	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SonSystemInformationBlockType2_117[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, ssfnCycle),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_ssfnCycle_constr_118,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"ssfnCycle"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, currentNodeId),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_currentNodeId_constr_119,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"currentNodeId"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, messageSequenceNumber),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_messageSequenceNumber_constr_120,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"messageSequenceNumber"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, currentNodeLeaveIndication),
		&asn_DEF_currentNodeLeaveIndication_121,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"currentNodeLeaveIndication"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, subnetInfo),
		&asn_DEF_SubnetInfo,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"subnetInfo"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, currentNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"currentNodeAddress"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SonSystemInformationBlockType2, mainNodeAddress),
		&asn_DEF_NodeAddressIdentity,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"mainNodeAddress"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonSystemInformationBlockType2, occupiedRadioFrameList),
		&asn_DEF_OccupiedRadioFrameList,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"occupiedRadioFrameList"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SonSystemInformationBlockType2, nonCriticalExtension),
		&asn_DEF_nonCriticalExtension_128,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nonCriticalExtension"
#endif
	},
};
static const uint8_t asn_MAP_SonSystemInformationBlockType2_oms_117[] = { 7, 8 };
static asn_SEQUENCE_specifics_t asn_SPC_SonSystemInformationBlockType2_specs_117 = {
	sizeof(struct SonSystemInformationBlockType2),
	asn_MAP_SonSystemInformationBlockType2_oms_117,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SonSystemInformationBlockType2 = {
#ifdef _ASN1_DEBUG_MODE_
	"SonSystemInformationBlockType2",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SonSystemInformationBlockType2_117,
	9,	/* Elements count */
	&asn_SPC_SonSystemInformationBlockType2_specs_117	/* Additional specs */
};

/******  SonSystemInformationBlockType2 Implement End *****/

/******  OccupiedRadioFrameList Implement Start *****/
static asn_per_constraints_t asn_PER_type_OccupiedRadioFrameList_constr_129 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  32,  32 }	/* (SIZE(32..32)) */
};
static asn_TYPE_member_t asn_MBR_OccupiedRadioFrameList_129[] = {
	{ ATF_POINTER, 0, 0,
		&asn_DEF_OccupiedPerRadioFrame,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		""
#endif
	},
};
static asn_SET_OF_specifics_t asn_SPC_OccupiedRadioFrameList_specs_129 = {
	sizeof(struct OccupiedRadioFrameList),
};
asn_TYPE_descriptor_t asn_DEF_OccupiedRadioFrameList = {
#ifdef _ASN1_DEBUG_MODE_
	"OccupiedRadioFrameList",
#endif
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	&asn_PER_type_OccupiedRadioFrameList_constr_129,
	asn_MBR_OccupiedRadioFrameList_129,
	1,	/* Single element */
	&asn_SPC_OccupiedRadioFrameList_specs_129	/* Additional specs */
};

/******  OccupiedRadioFrameList Implement End *****/

/******  OccupiedPerRadioFrame Implement Start *****/
static asn_TYPE_member_t asn_MBR_OccupiedPerRadioFrame_131[] = {
	{ ATF_POINTER, 1, offsetof(struct OccupiedPerRadioFrame, fixedOccupiedPerRadioFrame),
		&asn_DEF_FixedOccupiedPerRadioFrame,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"fixedOccupiedPerRadioFrame"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct OccupiedPerRadioFrame, dynamicOccupiedPerRadioFrame),
		&asn_DEF_DynamicOccupiedPerRadioFrame,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"dynamicOccupiedPerRadioFrame"
#endif
	},
};
static const uint8_t asn_MAP_OccupiedPerRadioFrame_oms_131[] = { 0, 1 };
static asn_SEQUENCE_specifics_t asn_SPC_OccupiedPerRadioFrame_specs_131 = {
	sizeof(struct OccupiedPerRadioFrame),
	asn_MAP_OccupiedPerRadioFrame_oms_131,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_OccupiedPerRadioFrame = {
#ifdef _ASN1_DEBUG_MODE_
	"OccupiedPerRadioFrame",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_OccupiedPerRadioFrame_131,
	2,	/* Elements count */
	&asn_SPC_OccupiedPerRadioFrame_specs_131	/* Additional specs */
};

/******  OccupiedPerRadioFrame Implement End *****/

/******  FixedOccupiedPerRadioFrame Implement Start *****/
static asn_per_constraints_t asn_PER_memb_metric_constr_135 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_nodeSN_constr_137 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */
};
static asn_TYPE_member_t asn_MBR_FixedOccupiedPerRadioFrame_134[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FixedOccupiedPerRadioFrame, metric),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_metric_constr_135,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"metric"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct FixedOccupiedPerRadioFrame, parameter),
		&asn_DEF_Parameter,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"parameter"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct FixedOccupiedPerRadioFrame, nodeSN),
		&asn_DEF_OCTET_STRING,
		&asn_PER_memb_nodeSN_constr_137,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nodeSN"
#endif
	},
};
static const uint8_t asn_MAP_FixedOccupiedPerRadioFrame_oms_134[] = { 1 };
static asn_SEQUENCE_specifics_t asn_SPC_FixedOccupiedPerRadioFrame_specs_134 = {
	sizeof(struct FixedOccupiedPerRadioFrame),
	asn_MAP_FixedOccupiedPerRadioFrame_oms_134,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FixedOccupiedPerRadioFrame = {
#ifdef _ASN1_DEBUG_MODE_
	"FixedOccupiedPerRadioFrame",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_FixedOccupiedPerRadioFrame_134,
	3,	/* Elements count */
	&asn_SPC_FixedOccupiedPerRadioFrame_specs_134	/* Additional specs */
};

/******  FixedOccupiedPerRadioFrame Implement End *****/

/******  Parameter Implement Start *****/
static asn_per_constraints_t asn_PER_memb_dataArrivalRate_constr_139 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_Parameter_138[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Parameter, dataArrivalRate),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_dataArrivalRate_constr_139,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"dataArrivalRate"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_Parameter_specs_138 = {
	sizeof(struct Parameter),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Parameter = {
#ifdef _ASN1_DEBUG_MODE_
	"Parameter",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_Parameter_138,
	1,	/* Elements count */
	&asn_SPC_Parameter_specs_138	/* Additional specs */
};

/******  Parameter Implement End *****/

/******  DynamicOccupiedPerRadioFrame Implement Start *****/
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
conflictIndication_142_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static asn_dec_rval_t
conflictIndication_142_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	conflictIndication_142_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
conflictIndication_142_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	conflictIndication_142_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_conflictIndication_constr_142 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_nodeId_constr_141 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static const asn_INTEGER_enum_map_t asn_MAP_conflictIndication_value2enum_142[] = {
	{ 0 },
	{ 1 }
};
static const uint8_t asn_MAP_conflictIndication_enum2value_142[] = {
	0,	/* false(0) */
	1	/* true(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_conflictIndication_specs_142 = {
	asn_MAP_conflictIndication_value2enum_142,	/* "tag" => N; sorted by tag */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	0
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_conflictIndication_142 = {
#ifdef _ASN1_DEBUG_MODE_
	"conflictIndication",
#endif
	conflictIndication_142_decode_uper,
	conflictIndication_142_encode_uper,
	&asn_PER_type_conflictIndication_constr_142,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_conflictIndication_specs_142	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DynamicOccupiedPerRadioFrame_140[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DynamicOccupiedPerRadioFrame, nodeId),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_nodeId_constr_141,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nodeId"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct DynamicOccupiedPerRadioFrame, conflictIndication),
		&asn_DEF_conflictIndication_142,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"conflictIndication"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_DynamicOccupiedPerRadioFrame_specs_140 = {
	sizeof(struct DynamicOccupiedPerRadioFrame),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DynamicOccupiedPerRadioFrame = {
#ifdef _ASN1_DEBUG_MODE_
	"DynamicOccupiedPerRadioFrame",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_DynamicOccupiedPerRadioFrame_140,
	2,	/* Elements count */
	&asn_SPC_DynamicOccupiedPerRadioFrame_specs_140	/* Additional specs */
};

/******  DynamicOccupiedPerRadioFrame Implement End *****/

/******  NodeRouteInformation Implement Start *****/
static asn_TYPE_member_t asn_MBR_NodeRouteInformation_145[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NodeRouteInformation, nodeRouteInfo),
		&asn_DEF_OCTET_STRING,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nodeRouteInfo"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_NodeRouteInformation_specs_145 = {
	sizeof(struct NodeRouteInformation),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NodeRouteInformation = {
#ifdef _ASN1_DEBUG_MODE_
	"NodeRouteInformation",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_NodeRouteInformation_145,
	1,	/* Elements count */
	&asn_SPC_NodeRouteInformation_specs_145	/* Additional specs */
};

/******  NodeRouteInformation Implement End *****/

/******  ActiveTime Implement Start *****/
static asn_per_constraints_t asn_PER_memb_ssfnCycle_constr_148 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_ssfn_constr_149 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 14,  14,  0,  10239 }	/* (0..10239) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_ActiveTime_147[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveTime, ssfnCycle),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_ssfnCycle_constr_148,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"ssfnCycle"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct ActiveTime, ssfn),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_ssfn_constr_149,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"ssfn"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_ActiveTime_specs_147 = {
	sizeof(struct ActiveTime),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ActiveTime = {
#ifdef _ASN1_DEBUG_MODE_
	"ActiveTime",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_ActiveTime_147,
	2,	/* Elements count */
	&asn_SPC_ActiveTime_specs_147	/* Additional specs */
};

/******  ActiveTime Implement End *****/

/******  NodeAddressIdentity Implement Start *****/
static asn_per_constraints_t asn_PER_memb_nodeSN_constr_151 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */
};
static asn_TYPE_member_t asn_MBR_NodeAddressIdentity_150[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NodeAddressIdentity, nodeSN),
		&asn_DEF_OCTET_STRING,
		&asn_PER_memb_nodeSN_constr_151,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"nodeSN"
#endif
	},
};
static asn_SEQUENCE_specifics_t asn_SPC_NodeAddressIdentity_specs_150 = {
	sizeof(struct NodeAddressIdentity),
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NodeAddressIdentity = {
#ifdef _ASN1_DEBUG_MODE_
	"NodeAddressIdentity",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_NodeAddressIdentity_150,
	1,	/* Elements count */
	&asn_SPC_NodeAddressIdentity_specs_150	/* Additional specs */
};

/******  NodeAddressIdentity Implement End *****/

/******  SubnetInfo Implement Start *****/
static asn_per_constraints_t asn_PER_memb_physCellId_constr_153 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  503 }	/* (0..503) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_per_constraints_t asn_PER_memb_subnetFreq_constr_154 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_SubnetInfo_152[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubnetInfo, physCellId),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_physCellId_constr_153,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"physCellId"
#endif
	},
	{ ATF_NOFLAGS, 0, offsetof(struct SubnetInfo, subnetFreq),
		&asn_DEF_NativeInteger,
		&asn_PER_memb_subnetFreq_constr_154,
		0,
#ifdef _ASN1_DEBUG_MODE_
		"subnetFreq"
#endif
	},
	{ ATF_POINTER, 1, offsetof(struct SubnetInfo, leaveTime),
		&asn_DEF_ActiveTime,
		0,	/* No PER visible constraints */
		0,
#ifdef _ASN1_DEBUG_MODE_
		"leaveTime"
#endif
	},
};
static const uint8_t asn_MAP_SubnetInfo_oms_152[] = { 2 };
static asn_SEQUENCE_specifics_t asn_SPC_SubnetInfo_specs_152 = {
	sizeof(struct SubnetInfo),
	asn_MAP_SubnetInfo_oms_152,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SubnetInfo = {
#ifdef _ASN1_DEBUG_MODE_
	"SubnetInfo",
#endif
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* No PER visible constraints */
	asn_MBR_SubnetInfo_152,
	3,	/* Elements count */
	&asn_SPC_SubnetInfo_specs_152	/* Additional specs */
};

/******  SubnetInfo Implement End *****/

